### ISSUE TITLE
extractMoreauBroto fails when the sequence is shorter than the lag

### ISSUE THREAD

**Issue by koefoed** [road2stat/protr#2]
extractMoreauBroto fails when nchar(x) <= nlag without a propper error message:

```R
> packageVersion('protr')
[1] ‘0.5.1’
> extractMoreauBroto("STHIYTKE")
Error in P[[i]][1:(N - j)] : 
  only 0's may be mixed with negative subscripts
```

**Comment by VeenaPulicharla** [comment]
Hi, I don't belong to Bioinformatics background, I am trying this package for some project, I have peptide sequences, I would like to derive some features from it to use as input to machine learning model. Could someone explain the reason for this error, 
"extractMoreauBroto: length of the sequence is <= nlag; NAs will be generated", 

- why it doesn't accept sequences with shorter length ?

- what are the min and max limits for sequence length limits?

- I have many sequences with length in range of 5 to 25, how to extract features from these sequences, any suggestions?
